name: ebook_reader
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^10.2.3
  archive: ^3.6.1
  xml: ^6.5.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  google_sign_in: ^7.1.1
  cloud_firestore: ^6.0.0
  flutter_tts: ^4.0.0
  web: ^1.1.1
  http: ^1.2.2
  html: ^0.15.4
  crypto: ^3.0.3
  collection: ^1.18.0
  meta: ^1.12.0
  shared_preferences: ^2.5.3
  flutter_cache_manager: ^3.3.1  # NEW for image caching
  google_fonts: ^6.2.1
  path_provider: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
