name: Android Release (Vidya)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Print versions (debug)
        run: |
          which flutter
          flutter --version
          java -version
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"

      # Create android/local.properties with the ACTUAL flutter sdk path
      - name: Create android/local.properties
        run: |
          mkdir -p android
          FLUTTER_BIN="$(which flutter)"
          # /opt/hostedtoolcache/flutter/.../flutter/bin/flutter -> /opt/.../flutter
          FLUTTER_SDK="$(dirname "$(dirname "$FLUTTER_BIN")")"
          {
            echo "flutter.sdk=$FLUTTER_SDK"
            echo "sdk.dir=$ANDROID_SDK_ROOT"
          } > android/local.properties
          echo "---- android/local.properties ----"
          cat android/local.properties

      # Fail early if any signing secret is missing
      - name: Validate signing secrets
        run: |
          [ -n "${{ secrets.KEYSTORE_BASE64 }}" ] || (echo "Missing KEYSTORE_BASE64" && exit 1)
          [ -n "${{ secrets.KEYSTORE_PASSWORD }}" ] || (echo "Missing KEYSTORE_PASSWORD" && exit 1)
          [ -n "${{ secrets.KEY_ALIAS }}" ] || (echo "Missing KEY_ALIAS" && exit 1)
          [ -n "${{ secrets.KEY_PASSWORD }}" ] || (echo "Missing KEY_PASSWORD" && exit 1)

      - name: Decode keystore
        run: |
          mkdir -p android/app
          echo "$KEYSTORE_BASE64" | base64 --decode > android/app/vidya.jks
          ls -lh android/app/vidya.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      # Optional sanity check; if wrong password/alias, this step will fail early with a clear message
      - name: Verify keystore
        run: |
          keytool -list -keystore android/app/vidya.jks -storepass "${{ secrets.KEYSTORE_PASSWORD }}" -alias "${{ secrets.KEY_ALIAS }}" -v | head -n 20

      - name: Create key.properties
        run: |
          cat > android/key.properties <<'PROP'
          storeFile=android/app/vidya.jks
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          PROP
          echo "---- android/key.properties ----"
          sed 's/=.*/=****/' android/key.properties

      # Force-disable google-services plugin in CI to avoid json/package mismatches
      - name: Disable google-services plugin for CI
        run: |
          sed -i 's/id("com.google.gms.google-services")//g' android/app/build.gradle.kts || true
          sed -i 's/^.*com.google.gms.google-services.*apply false.*$//g' android/settings.gradle.kts || true

      - name: Flutter pub get
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release -v

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: vidya-apk
          path: build/app/outputs/flutter-apk/*.apk
