name: Android Release (Vidya)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Run shell steps from the Flutter project folder
    defaults:
      run:
        working-directory: ebook_reader

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Create android/local.properties
        run: |
          mkdir -p android
          {
            echo "flutter.sdk=$FLUTTER_HOME"
            echo "sdk.dir=$ANDROID_SDK_ROOT"
          } > android/local.properties

      - name: Decode keystore
        if: ${{ secrets.KEYSTORE_BASE64 != '' }}
        run: |
          mkdir -p android/app
          echo "$KEYSTORE_BASE64" | base64 --decode > android/app/vidya.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Create key.properties
        if: ${{ secrets.KEYSTORE_BASE64 != '' }}
        run: |
          cat > android/key.properties <<'PROP'
          storeFile=android/app/vidya.jks
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          PROP

      - name: Create lib/secrets.dart
        run: |
          mkdir -p lib
          cat > lib/secrets.dart <<'DART'
          /// Generated by CI. Do not commit secrets.
          const String openAIApiKey =
              String.fromEnvironment('OPENAI_API_KEY', defaultValue: '');
          DART

      # If you don't have android/app/google-services.json for com.joydeep.vidya,
      # you can disable the plugin during CI by uncommenting below.
      # - name: Disable google-services plugin (optional)
      #   run: |
      #     sed -i 's/id("com.google.gms.google-services")//g' android/app/build.gradle.kts || true
      #     sed -i 's/id("com.google.gms.google-services")//g' android/settings.gradle.kts || true

      - name: Build release APK
        run: flutter build apk --release --dart-define=OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: vidya-apk
          path: build/app/outputs/flutter-apk/*.apk
